spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
    continue-on-error: true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console