spring:
  datasource:
    username: vacation_admin
    password: vacation_admin
    url: jdbc:postgresql://127.0.0.1:5432/vacation_manager
    driver-class-name: org.postgresql.Driver
    platform: postgres